import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function AccordionHome() {
  return (
    <div className="container mx-auto mb-8">
      <h1 className="text-center text-2xl md:text-4xl font-medium mb-2 md:mb-4">
        Frequently Asked Questions
      </h1>
      <Accordion type="single" collapsible className="w-full border px-6 py-2">
        <AccordionItem value="item-1">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            What is this website about?
          </AccordionTrigger>
          <AccordionContent>
            This website leverages AI to generate high-quality, contextually
            relevant text for a variety of applications, from content creation
            to personalized communication.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-2">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            Is the generated content unique?
          </AccordionTrigger>
          <AccordionContent>
            Absolutely. Each piece of text generated by our AI is unique and
            tailored to your specific input, ensuring that your content stands
            out.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-3">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            How secure is my data?
          </AccordionTrigger>
          <AccordionContent>
            We prioritize your privacy and security. All data is processed
            securely, and we do not store your input or generated content longer
            than necessary to provide our services.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-4">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            Can the AI generate text in multiple languages?
          </AccordionTrigger>
          <AccordionContent>
            Yes, our AI supports text generation in multiple languages. You can
            select your preferred language during the input stage.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-5">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            How do I get started?
          </AccordionTrigger>
          <AccordionContent>
            Getting started is easy! Simply sign up for an account, and start
            generating text. Our user-friendly interface will guide you through
            the process.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-6">
          <AccordionTrigger className="text-base text-left md:text-xl font-normal">
            Can I customize the generated text?
          </AccordionTrigger>
          <AccordionContent>
            Yes, you can customize the generated text to fit your specific style
            or requirements. The AI provides a flexible base that you can easily
            tweak to match your preferences.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}
