import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Header/Navbar";
import AuthProvider from "@/services/AuthProvider";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  icons: {
    icon: "/assets/images/icon.png",
  },
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar></Navbar>
          <hr />
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
